name: "Release (auth)"

# To test this out, push a tag with a pre-release version. The version number
# should be the version number of the next actual release.
#
# > When major, minor, and patch are equal, a pre-release version has lower
# > precedence than a normal version:
# >
# > Example: 1.0.0-alpha < 1.0.0.
# >
# > - https://semver.org
#
# So if the next release we intend to put out is 1.2.3, you can:
#
#     git tag auth-v1.2.3-test
#     git push origin auth-v1.2.3-test
#
# We use a suffix like `-test` to indicate that these are test tags, and that
# they belong to a pre-release.
#
# If you need to do multiple tests, add a +x at the end of the tag. e.g.
# `auth-v1.2.3-test+1`.
#
# Once the testing is done, also delete the tag(s) please.

on:
    push:
        branch: ["x-workflow-test"]
        tags:
            - "auth-v*"

env:
    FLUTTER_VERSION: "3.16.9"

jobs:
    build-test:
        runs-on: ubuntu-latest
        steps:
            - run: echo "ref is ${{ github.ref }}"
            - run: echo "tag is ${{ github.event.release.tag_name }}"
            - name: Dump env
              run: env | sort
            - name: Dump GitHub context
              run: env | sort
              env:
                GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
            - name: Build Android APK
              run: |
                  echo artifacts/ente-${{ github.event.release.tag_name }}.apk
                  echo "artifacts/ente-${{ github.event.release.tag_name }}.apk"
                  echo "${{ github.event.release.tag_name }}"
                  echo ${{ github.event.release.tag_name }}
            - name: Build Android APK 2
              run: echo ${{ github.event.release.tag_name }}
